apiVersion: kyverno.octokode.io/v1alpha1
kind: KyvernoArtifact
metadata:
  labels:
    app.kubernetes.io/name: kyverno-artifact-operator
    app.kubernetes.io/managed-by: kustomize
  name: kyvernoartifact-artifactory-sample
  namespace: kyverno-artifact-operator-system
spec:
  url: trialwhj9in.jfrog.io/kyverno-oci-local/kyverno-oci
  type: oci
  provider: artifactory
  pollingInterval: 60
